using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DutchmanSite.Helper
{
    public class StromgardPrompt
    {
        private List<string> PromptList = new List<string> {
                "Four Dvergr hold up each corner of the sky, frozen with their burden in perpetuity.  Interacting with or even talking about them has been strictly forbidden in dwarven culture for unknown reasons.",
                "Odin asks the dwarves to procure a legendary material for the building of the first humans.  Because he wishes them to be upstanding and civilized, he requests that the most valorious be the ones to bring it to him.",
                "At the end of the Aesir-Vanir war, the gods agreed to exchange hostages to broker peace between both groups.  Hoenir and Mimir were traded by the Aesir for Freyr, Njord, and Freya- a stacked trade in the Aesir's favor.  A party of neutral background is needed to oversee the tense transaction.",
                "The cosmic void between Muspelheim and Niflheim is called the Ginnungagap.  It is mind-bendingly immense and still as death, driving mortals who lay eyes on it mad and gods to dispair.",
                "Norns guard the wells of knowledge scattered around Yggdrasil.  A single drink from such a well grants unbelivable wisdom but the Norns charge a steep price even if they deem someone worthy enough to drink.",
                "To learn the reading of runes, mortals symbolically mimic Odin's act of sacrificing an eye, stabbing himself, hanging upside down, and starving for nine days for the same knowledge.  Such an undertaking, even a mimicry, could mean life or death for the initiate.  But knowledge always comes with a price.",
                "The dwarven city of Vel was built underwater, off the glacial coast.  Once a paradise of masterworks and comfort, a huge shadow just past the light of the city's crystal walls is causing fear and paranoia to spread like fever.  Expeditions to identify and possibly slay the monstrous thing have turned up nothing so far and it has taken a toll on the city.",
                "There are more places the dead go than just Valhalla.  Folkvangr is the encampent field of Freya, home of the first warriors to be dispatched during Ragnarok.  Those who die at sea go to the goddess Ran and her underwater kingdom.  Helheim takes most of the dead, where they toil under Hel's rule.  For the dishonorable, Niflheim awaits- a blasted, frozen hellscape populated with distorted and tortured souls.",
                "A returning raiding party brings back a strange golden idol from distant shores.  In the form of some unknown animal, the idol brings catastrophe to whomever owns it.  To make matters worse it comes alive as a full size version of what it represents each bloodmoon.",
                "Under threat of death from Thor, after a prank gone wrong involving Sif's golden hair, Loki travels to the dwarves to barter for a replacement.  He has no intention of paying a fair price and is, actually, looking to leave with as many dwarven masterworks as possible.",
                "A master at exploiting loopholes, Loki once contrived a bet with two master smiths and claimed that he would gamble his head that they couldn't produce a treasure the same caliber as Skinbladnir- the folding ship with enchanted sails.  The smiths took him on and produced not one but three fantastic treasures- the golden ring Draupnir, the hammer Mjolnir, and Gullinbursti, the golden boar.  Loki took these treasures to the Aesir for favor but when the smiths came to collect their debt, he weaseled out, claiming that he had bet his head but not his neck and therefore the payment could not be made fairly.  The furious smiths, with Odin's blessing, settled for sewing Loki's mouth shut with enchanted thread.  This left Loki in the vulnerable position of requiring assistance to remove.",
                "Outcasts worship Loki as a deity who defies social norms and obligations.  While he doesn't typically deign to get involved in most mortal affairs, his tune changes when a large enough amount of chaos can be created.  More than just a simple trickster, Loki's actions seek to undermine the rule and order of the Asgardian gods.",
                "Above all, Odin craves wisdom and can be petitioned for a exchange of knowledge if a devotee can offer something of worth the god doesn't already know.",
                "The gods knew Fenrir was destined to eat the world.  As the wolf grew to monstrous sizes, the gods continually tricked him into letting them place fetters or chains on him to keep him in place.  Each time Fenrir broke free, the gods had to smile and praise his strength.  They finally petitioned the dwarves of Svartalheim to make them the strongest chains imaginable and were gifted with what looked like simple ribbon.  Fenrir was immediately suspicious of these new bindings and only agreed to remain still if someone stuck their hand in his mouth as insurance.  Grimly, Tyr agreed.  The bindings went on and Fenrir could not tear them apart.  Tyr lost his hand for the greater good and for the sancity of a bargain held.",
                "Once, Loki entered an eating contest with a J&oumltun.  A large board of meat was set on the table and the contestants were put at either end.  Whoever ate everything on their way to the center first was to be the winner.  Loki made it first, of course, but the J&oumltun had eaten <em>everything</em>- the meat, bones, and the board itself.  Despite being played at his own game, Loki was so delighted by this that he showered praise and blessings on the clever giant",
                "For a bet, Loki once said Thor wouldn't be able to lift a cat.  Thor tried- for <em>hours</em>- to heft a J&oumltun's pet cat but could not.  Not only did this cause paramount humiliation but once Thor discovered that Loki had magicked part of Jormungandr to appear as a small cat, he was enraged and nearly ended up murdering his half-brother.",
                "Prophetic dreams and sudden visions were a major method of communication between the gods and mortals.  Powerful messages were often experienced by multiple people or a wide area, depending on need and deity.",
                "The halfling village of Lauf was recently ransacked by bandits and a great many lives were lost.  Most of the inhabitants were largely defenseless during the assault.  The halflings mourn the loss of their dead but their allies- other villages and warriors spanning all peoples- vow to track down and bring the bandits to justice.  While many people believe that the hospitality halfings are famed for invites exploitation, there's no denying that it doesn't gain powerful allies and friendship.",
                "Odin's spear, Gungir, is enormouse and etched with intricate runes.  Made by the master craftspeople of Svartelheim, most can only guess the meaning of the delicate markings.  It can be certain, however, that they contain highly desireable, secret magic.",
                "Idun is the goddess that minds the orchards of Asgard.  The berry brambles she tends keep the gods young and ageless.  As such, she is dearly loved but also a prime target for the enemies of Asgard and a highly exploitable weakness.",
                "Thor's chariot was pulled by huge goats and these famous beasts could be eaten and revived the next morning by hammering their flesh and bones back together, offering their bodies for many a lively feast.  Once, a greedy dinner guest broke several bones to get to the marrow within and Thor was furious to discover that the goat was unable to be brought back to life.",
                "A bow made from a cutting of Yggdrasil by a banished J&oumltun is unimaginably powerful in the hands of a mortal who weilds it.  The gods are after it, however, and are violently seeking anyone who lays their hands upon it. ",
                "After the long and arduous Aesir-Vanir war, a truce was sealed by all the gods spitting into a vat.  The liquid took on a body and mind of its own, going as Kvasir.  This being was incredibly intelligent and could solve any problem passed before it.  Unfortunately, two dwarve came across it and slew it though in the process they discovered that Kvasir's blood still contained the essense of all its wisdome.  With it, they brewed the Mead of Poetry, a pricesless substance that grants incredible wisdom.  Odin particularly desires to track down the Mead, in hopes of gaining even more wisdom.",
                "It is common practice to accept money or holdings as reparations when a loved one is killed in battle or a duel instead of swearing vengeance.  Even the gods hold by this legal structure for the most part.  The goddess Skadi was granted numerous reparations for the murder of her father, even her choice of an Aesir husband.  Mortal affairs typically follow suit and additionally, the refusal to accept payment is usually seen as impractical and bloodthirsty.",
                "A J&oumltun with a deep grudge steals a body part from the one offending them.  Operating without it will be an inconvenience but not as difficult as retrieving it.",
                "Holmgang is trial-by-combat, wherein conflicts are decided soley on the victor.  Many make their living as Holmgang champions, representing their clients in the duel and taking part of the reward as payment.  Because victory in Holmgang is the deciding final and total deciding factor in deciding legal right, champions are well paid and respected.  Until they lose, of course.",
                "Someone has declared Holmgang against you.  You must now defend your honor and prove your innocence via one on one combat.  The person you face might be the offender themselves or their champion.  Losing this fight automatically brands you as guilty and the victor is entitled to a portion of their opponent's wealth as winnings.",
                "Returning vikings must take place in part of an involved cleansing ritual upon returning from a long voyage.  It is said to wash away the dangers of the open water and help seperate the worlds of battle and home.  It is also done to prepare lovers to be reunited and to attract new paramours.  Neglecting this ritual is said to awaken vengeful horrors from the sea.",
                "Because of their association with Freya, cats were considered messengers of her and usually treated as though the were sent to deliver news from the goddess.",
                "J&oumltnar are usually content to live and let live but occasionally, more vicious ones make themselves known by attacking settlements and eating their victims.",
                "In the early frosts, a phenomenon called Ghost Berries can occur.  As winter frosts coat berry bushes, ice freezes around the fruit which rots away.  This leaves a perfect ice replica in its place.  Typically this signified that the coming winter would be abnormally harsh.",
                "For those who can read runes, creating a personal set was a task of great ceremony and importance.  Shell, bone, wood, glass, and metal were all common components but no runes were as powerful as those made with appropriately powerful or rare materials.",
                "One of the most terrible curses for a skald is the stave of Fjold&oumystave, the sigil that compels the bearer to lie.  As the power of the rune takes hold, the bearer lies more often and the consequences build tremendously, usually resulting in the skald's painful and public death. ",
                "A powerful warrior has grown bored from lack of challenge.  A foreign phrase, 'fear gives you wings' has gripped their heart powerfully.  Convinced this may be their shot to rekindle the fire within them, the warrior sets about trying to experience fear in order to gain the power of flight.",
                "At sea, a group of warriors returning from conquest drag a humanoid figure from the surf to save it from drowning.  They are caught up in arguing about the strange creature's origins until a gigantic monster breaks the surface and demands its runaway child back.",
                "While embroiled in dangerous activities, a hasty funeral must be prepared for a fallen comrade.  Tradition demands that a warrior be placed with their belongings and either burned or sunk into the ocean (or both) for the rites to be completed and the soul protected from Hel.  There is little time to perform the rite, however, and fewer supplies to carry it out with.  To make matters worse, the deceased's belongings contain something that could serve the survivors tremendously, were they to commit the ultimate dishonor of keeping them.",
                "A Nithfir, an elf related to the immortal Alfir, has been spotted in one of the lower realms of Yggdrasil.  The Nithfir have been isolated for ages- since the end of the Aesir-Vanir conflict when they fell out with the Asgardians.  There are many rumors about their dislike of the other gods, along with the latent fear that they have or will ally themselves with blood-hungry J&oumtnar in order to throw the world out of balance.",
                "Dying is rarely the end of the story in Stromgard.  Where your soul winds up is a matter of vital import to most warriors.  If you ever broke a promise, commited a dishonorable murder, promised yourself to someone then betrayed their trust in someone else's bed... Any of these acts is enough to brand you dishonorable and condemn your soul to Lady Hel's jurisdiction.  For these crimes, she typically sent souls to Nastrond, a once-rocky shoreline that is now home to a mountain of corpses in massive dunes.  The dragon Nighoggr is said to lurk here, gnawing on the dessicated corpses and burrowing through the rubble.",
                "Trapped in a terrible cycle, a small island far off the coast is home to a terrible battle that repeats constantly.  Once, long ago, a Jarl's daughter was kidnapped while he was away on a raid.  Upon his return he immediately set out for his beloved girl and took nearly two years to locate her.  She had been held captive on this island but in the interim, had fallen in love and married the young chief there.  Initially, she was to be used as leverage against her father but the young chief had come to love her dearly and he and his warriors treated her with repsect and kindness.  When the girl's father arrived, she desperately tried to broker peace between her father, husband, and their armies.  She offered a valuable necklace but her father's sword had already been drawn.  The armies battled to the very last man and, overcome with grief, the girl resurrected all of them only to have the battle resume uninterrupted.  Again and again- even now- the battle continues until each soldier is killed and the girl revives them again, unable to bear the pain of loss.",
                "The ring of Advari is a terrible, sentient artifact that seduces all who wear it with whispers of power.  Unfortunately, this ring is interested in bringing bloodshed and grief, cursing all who cross its path with terrible tragedy.",
                "A powerful warlord from the far south is locked in combat with a nation that is often the victim of raiders coming out of Stromgard.  This presents an ideal opportunity to raze the coast for resources, as all attention is on this might horse lord at the border, thought the temptation to see him in action first hand is particularly strong.",
                "Witches sell their charms in nearly every settlement across Stromgard and one of the arts they deal in the process of making enchanted jewelery out of the flesh of their victims or sacrifices.  They say that strange magic can be worked in this fashion, that earrings made from real ears can grant the ability to hear another's voice across any distance, that rings made from finger bones can let the wearer transfer their touch elsewhere... Rumors say that tremendously useful skills can be purchased and used freely this way.",
                "Bonds of kinship are almost always considered sacred, but none as much as the Oath of Felag.  To invoke Felag with another is to declare that you are blood brothers, partners in financial matters, and honorbound to each other.  If one participant is ever deemed craven, the other will be as well.  Typically, this oath was undertaken to bestow honor or convey immense trust between warriors, as well as to strengthen the chain of command in a fleet of ships or contingent of warriors.  Breaking a Felag is considered one of the graves crimes one could commit.",
                "In dire times, a special sacrifice was performed to appease angry gods, spirits, or other forces.  Called the Blot, this ritual involved building a dais, appointing an overseer, and making an appropriate sacrifice.  Most of the time, this was livestock but in desperation, sometimes men, women, or children were used.  Monsters and beasts of particular strength were also occasionally used, depending on the force needing to be appeased.  The sacrifices were cleaned, annointed with oil or a balm of herbs, before ceremonial blood was drawn with a nonfatal wound.  Once this was all completed, the sacrifice would be committed to pyre.",
                "Erected for a single deity, the Horgar was a sacrifical mound made from stones or other materials as a place for people to worship.  They were usually on the small side and a single village typically had multiple Horgar for the worship of different entities.  The process of building a Horgar was a ritual unto itself, as each stone had to be placed with care, annointed with alcohol, and marked with an appropriate rune or stave.  This arduous undertaking could be challenging even for well-equipped villages and so the damaging of one- even by accident- is considerd a terrible offense.",
                "Most have heard the insult of <em>Ergi</em>, but if you really want a meadhall to go dead silent, call your opponent <em>nith</em> instead.  This potent insult essentially label's its target a thrall or mindless, happy slave, undermining their honor and even their personhood in one direct blow.  Invoking this word will likely have a near-instant effect and almost certainly result in a Holmgang if the offended party is feeling generous or an immediate brawl with intent to kill if they're not.",
                "Birth is incredibly important in a land so fraught with dangers.  Important rituals were carried out around new children with utmost solemnity as mistakes could doom the child to poor health or a dishonorable dispostion.  These things could further extend to dishonor or blemish the whole family and name as well, which is partially why these rites were taken so seriously.  For nine days after birth, the child and mother were to spend time in quietude, honoring Odin's wisdom and sacrifice for knowledge.  During this period, the rest of the family plan on naming the child and preparing to host a large feast to honor not only the child and recovering mother, but also the community at large.  Once the nine days are up, the child is annointed with sea water, honey, mead, or milk and their name is announced- usually taken from a god or deceased relative to tie their blood to something tangible and root them to the earth.  The neglect of these rituals could produce a child with no roots, no ties to keep them honorbound and righteous, only to bring suffering to those around them.",
                "Land wights are spirits tied down to specific locations all over the nine realms.  They are usually peaceful, dedicated to keeping the leand under their power flourishing and pristine.  Some who are magically inclined say that these wights are souls for certain dead, allowed to remain near the living world for providing someone unknown service to the goddess Hel.  Normally invisible, those who have certain sensitivites are able to see the vaguely humanoid figures of these spirits.  And, as they are usually benevolent, the wights are known for sometimes dispensing wisdom or other boons to those who prove worthy.",
                "The gnomes of Stromgard craft impossible, amazing things though it often comes with intense collateral damage.  Two summers ago they accidentially unleashed a giant mechanical cat powered by something that smelled terrible and was incredibly explosive.  Now, there are colored plumes of smoke rising from the nearest gnome village accompanied by ominous flashing lights.  The entire region is put on edge and waiting for whatever new horror they've created to make its presence known."
        };

        public string GetPrompt()
        {
            Random Rand = new Random();
            return PromptList[Rand.Next(0, PromptList.Count)];
        }
    }
}